from selenium import webdriver
driver = webdriver.Chrome()
driver.implicitly_wait(5)
driver.maximize_window()
driver.get("https://practice.automationtesting.in/")
driver.execute_script("window.scrollTo(0, 600)")
driver.find_element_by_xpath("//h3[text()='Selenium Ruby']").click()
driver.find_element_by_xpath("//a[text()='Reviews (0)']").click()
driver.find_element_by_class_name("star-5").click()
driver.find_element_by_id("comment").send_keys("Nice book!")
driver.find_element_by_id("author").send_keys("Ivan Petrov")
driver.find_element_by_id("email").send_keys("test@gmail.com")
driver.find_element_by_id("submit").click()
driver.quit()